export const QUERY_KEY = {
  GET_ALL_STRATEGY: 'GET_ALL_STRATEGY',
  GET_USED_COUNT: 'GET_USED_COUNT',
  GET_ALL_AGENT: 'GET_ALL_AGENT',
  GET_AGENT_METADATA: 'GET_AGENT_METADATA',
  GET_AGENT_STAT: 'GET_AGENT_STAT',
  GET_AGENT_PORTFOLIO_ACTIVITY: 'GET_AGENT_PORTFOLIO_ACTIVITY',
  GET_AGENT_PORTFOLIO_HOLDINGS: 'GET_AGENT_PORTFOLIO_HOLDINGS',
  GET_AGENT_DASHBOARD: 'GET_AGENT_DASHBOARD',
  GET_AGENT_BUBBLE_DASHBOARD: 'GET_AGENT_BUBBLE_DASHBOARD',
  GET_AGENT_DATA: 'GET_AGENT_DATA',
  GET_AGENT_DATA_BY_ID: 'GET_AGENT_DATA_BY_ID',
  GET_AGENT_TOP_PICK: 'GET_AGENT_TOP_PICK',
  GET_AGENT_BY_TOKEN_SYMBOL: 'GET_AGENT_BY_TOKEN_SYMBOL',
};

export const MUTATION_KEY = {
  LOGIN: 'LOGIN',
  CREATE_STRATEGY: 'CREATE_STRATEGY',
  DELETE_COOKIE: 'DELETE_COOKIE',
  SEARCH_AGENT_BY_TOKEN_SYMBOL: 'SEARCH_AGENT_BY_TOKEN_SYMBOL',
};

export const API_RESPONSE_CODE = {
  GET: 200,
  POST: 201,
  DELETE: 204,
  PATCH: 204,
};
