export const ENV = {
  SERP_API_KEY: 'SERP_API_KEY',
  TAVILY_API_KEY: 'TAVILY_API_KEY',
  OPENAI_API_KEY: 'OPENAI_API_KEY',
  INSTANTNODE_API_KEY: 'INSTANTNODE_API_KEY',
  HELIUS_API_KEY: 'HELIUS_API_KEY',
  QUICKNODE_QPI_KEY: 'QUICKNODE_QPI_KEY',
  TWITTER_BEARER_TOKEN: 'TWITTER_BEARER_TOKEN',
  MARKET_ANALYSIS_MODEL_ID: 'MARKET_ANALYSIS_MODEL_ID',
  SENTIMENT_ANALYSIS_MODEL_ID: 'SENTIMENT_ANALYSIS_MODEL_ID',
} as const;
