FROM node:20-alpine

# Install dependencies for wrtc
RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    libc6-compat \
    libstdc++ \
    linux-headers \
    git

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

CMD ["npm", "run", "start:prod"] 