export const CONSTANTS = {
  CAP_POINT_POOL_IN: 10,
  CAT_POINT_COMMENTS: 20,

  POINT_SHARE: 30,
  POINT_WINNER: 10000,
  POINT_POOL_IN: 100,
  POINT_COMMENTS: 50,

  GRADE_AA: 4,
  GRADE_A: 3,
  GRADE_B: 2.5,
  GRADE_C: 2,
  GRADE_D: 1,
  BALANCE_GRADE_A: 3,
  BALANCE_GRADE_B: 2,
  BALANCE_GRADE_C: 1,
};
